# --- 基本站点配置 ---
baseURL: "https://lanshi.xyz/"
languageCode: "zh-cn"
defaultContentLanguage: "zh-cn"
title: "lanshi个人博客"
theme: "PaperMod"
enableEmoji: true
disableHugoGeneratorInject: true
sectionPagesMenu: "main"
googleAnalytics: "G-B5B8VFF5M8"
busuanzi:
  enable: true
buildDrafts: false

# --- 资源压缩 ---
minify:
  disableXML: true
  minifyOutput: true

# --- 菜单配置 ---
menu:
  main:
    - identifier: "resume"
      name: "简历"
      url: "/resume/"
      weight: 1
    - identifier: "portfolio"
      name: "作品集"
      url: "/portfolio/"
      weight: 2
    - identifier: "studynotes"
      name: "学习笔记"
      url: "/studynotes/"
      weight: 3
    - identifier: "posts"
      name: "文章"
      url: "/posts/"
      weight: 4
    - identifier: "statistics"
      name: "统计"
      url: "/statistics/"
      weight: 5
    - identifier: "archives"
      name: "归档"
      url: "/archives"
      weight: 25
    - identifier: "search"
      name: "搜索"
      url: "/search/"
      weight: 28

# --- 网站参数配置 ---
params:
  author: "烂石"
  description: "记录IT学习资源、教程和个人作品展示。"
  keywords: ["编程", "博客", "IT教程", "学习记录", "PaperMod", "作品集"]
  defaultTheme: "auto"
  disableThemeToggle: false
  logo: "/images/logo.png"
  showReadingTime: true
  showToc: true
  tocOpen: false
  headerDepth: 2
  enableGitInfo: true
  canonifyURLs: true
  disableScrollToTop: false
  codeEditable: true
  livePreview: true
  fastSearch: true
  enableTaxonomies: true
  assets:
    disableFingerprinting: true
    favicon: "/favicon.ico"
    disableHLJS: false
  navbar:
    enable: true
    search: true
    languageMenu: false
    darkModeMenu: true
  socialIcons:
    - name: "bilibili"
      url: "https://space.bilibili.com/176072673?spm_id_from=333.1007.0.0"
    - name: "tiktok"
      url: "https://v.douyin.com/i5BEn6SC/"
    - name: "wechat"
      url: "https://img.picui.cn/free/2025/03/01/67c2a41a25b39.jpg"
    - name: "qq"
      url: "https://qm.qq.com/q/NAXbuT3rQA"
    - name: "github"
      url: "https://github.com/lanshi17"
  ShowShareButtons: true
  ShareButtons: ["wechat", "qq", "bilibili", "github", "tiktok"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  hideCopyright: false
  enableWordCountChart: true
  math: "katex"
  comments:
    enabled: true
    provider: "giscus"
    giscusConfig:
      repo: "lanshi47/Blog_comments"
      repoID: "R_kgDOOBWQzw"
      category: "Announcements"
      categoryID: "DIC_kwDOOBWQz84Cnc1e"
      mapping: "pathname"
      reactionsEnabled: true
      emitMetadata: false
      theme: "preferred_color_scheme"
  share:
    wechat: true
    qq: true
    tiktok: true
    github: true
    bilibili: true
  profileMode:
    enabled: false
    title: "lanshi的个人博客"
    subtitle: "记录IT学习资源、教程和个人作品，分享我的技术之旅"
    imageUrl: "/images/profile.png"
    imageTitle: "lanshi 头像"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: "作品集"
        url: "/portfolio/"
      - name: "学习笔记"
        url: "/studynotes/"
      - name: "文章"
        url: "/posts/"
      - name: "简历"
        url: "/resume/"
      - name: "Github"
        url: "https://github.com/lanshi17"
  sitemap:
    changefreq: "daily"
    priority: 0.5
  homeInfoParams:
    enabled: true
    Title: "欢迎来到lanshi的个人博客"
    Content: "Welcome to lanshi's blog"
  fusejs:
    highlight: false
  markup:
    highlight:
      noClasses: false
      style: "github-dark-default"
  cover:
    hidden: false
  editPost:
    URL: "https://github.com/lanshi17/hugo_blog/tree/master/content"
    Text: "Suggest Changes"
    appendFilePath: true
  search:
    enabled: true
    engine: "fusejs"
    placeholder: "搜索文章..."
    maxResultsPerSection: 10
    liveReload: true
    highlightMatches: true
    showEmptyResult: true
    indexFile: "index.json"
    fuseOpts:
      tokenize: true
      matchAllTokens: true
      minMatchCharLength: 2
      threshold: 0.3
      distance: 100
      ignoreLocation: true
  outputFormats:
    JSON:
      mediaType: "application/json"
      baseName: "index"
      isPlainText: true
      notAlternative: true
  outputs:
    home: ["HTML", "RSS", "JSON"]
  listStyle:
    cardLayout: true
    hoverEffect: true
    compactTags: true

# --- 构建配置 ---
buildFuture: false
buildExpired: false

# --- 环境变量 ---
env: "production"
